package gaspoverka;

import javax.swing.*;
import javax.swing.UIManager;

public class Main extends javax.swing.JFrame {

    

    public Main() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PovButton = new javax.swing.JButton();
        IzmButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Att = new javax.swing.JMenu();
        AttIzm = new javax.swing.JMenuItem();
        AttCal = new javax.swing.JMenuItem();
        AttPov = new javax.swing.JMenuItem();
        Arch = new javax.swing.JMenu();
        ArchCounter = new javax.swing.JMenuItem();
        ArchRef = new javax.swing.JMenuItem();
        ArchSens = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ЗАО \"Белавтоматикасервис\" - ГАЗ-Поверка");
        setResizable(false);

        PovButton.setText("Поверка");
        PovButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PovButtonActionPerformed(evt);
            }
        });

        IzmButton.setText("Измерение");
        IzmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzmButtonActionPerformed(evt);
            }
        });

        Att.setText("Аттестация");

        AttIzm.setText("Измерение");
        AttIzm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttIzmActionPerformed(evt);
            }
        });
        Att.add(AttIzm);

        AttCal.setText("Калибровка");
        AttCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttCalActionPerformed(evt);
            }
        });
        Att.add(AttCal);

        AttPov.setText("Поверка");
        AttPov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttPovActionPerformed(evt);
            }
        });
        Att.add(AttPov);

        jMenuBar1.add(Att);

        Arch.setText("Архив");

        ArchCounter.setText("Счетчики");
        ArchCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchCounterActionPerformed(evt);
            }
        });
        Arch.add(ArchCounter);

        ArchRef.setText("Эталоны");
        ArchRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchRefActionPerformed(evt);
            }
        });
        Arch.add(ArchRef);

        ArchSens.setText("Сенсоры");
        ArchSens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchSensActionPerformed(evt);
            }
        });
        Arch.add(ArchSens);

        jMenuBar1.add(Arch);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PovButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IzmButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(PovButton)
                .addGap(26, 26, 26)
                .addComponent(IzmButton)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttIzmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttIzmActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attestation().setVisible(true);
            }
        });
    }//GEN-LAST:event_AttIzmActionPerformed

    private void ArchCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchCounterActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCounters().setVisible(true);
            }
        });
    }//GEN-LAST:event_ArchCounterActionPerformed

    private void ArchRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchRefActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRefrence().setVisible(true);
            }
        });
    }//GEN-LAST:event_ArchRefActionPerformed

    private void ArchSensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchSensActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSensors().setVisible(true);
            }
        });
    }//GEN-LAST:event_ArchSensActionPerformed

    private void PovButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PovButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoverkaPov().setVisible(true);
            }
        });
    }//GEN-LAST:event_PovButtonActionPerformed

    private void IzmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzmButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoverkaIzm().setVisible(true);
            }
        });
    }//GEN-LAST:event_IzmButtonActionPerformed

    private void AttCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttCalActionPerformed
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AttCal().setVisible(true);
            }
        });
    }//GEN-LAST:event_AttCalActionPerformed

    private void AttPovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttPovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AttPovActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Arch;
    private javax.swing.JMenuItem ArchCounter;
    private javax.swing.JMenuItem ArchRef;
    private javax.swing.JMenuItem ArchSens;
    private javax.swing.JMenu Att;
    private javax.swing.JMenuItem AttCal;
    private javax.swing.JMenuItem AttIzm;
    private javax.swing.JMenuItem AttPov;
    private javax.swing.JButton IzmButton;
    private javax.swing.JButton PovButton;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
