package gaspoverka;

import javax.swing.*;
import javax.swing.UIManager;

public class Main extends javax.swing.JFrame {

    

    public Main() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PovButton = new javax.swing.JButton();
        IzmButton = new javax.swing.JButton();
        AttButton = new javax.swing.JButton();
        repButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Arch = new javax.swing.JMenu();
        ArchDev = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ЗАО \"Белавтоматикасервис\" - ГАЗ-Поверка");
        setResizable(false);

        PovButton.setText("Поверка");
        PovButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PovButtonActionPerformed(evt);
            }
        });

        IzmButton.setText("Измерение");
        IzmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzmButtonActionPerformed(evt);
            }
        });

        AttButton.setText("Аттестация");
        AttButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttButtonActionPerformed(evt);
            }
        });

        repButton.setText("Отчеты");

        Arch.setText("Архив");

        ArchDev.setText("Устройства");
        ArchDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchDevActionPerformed(evt);
            }
        });
        Arch.add(ArchDev);

        jMenuBar1.add(Arch);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(AttButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(repButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(IzmButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(PovButton, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(PovButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IzmButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(repButton)
                .addGap(42, 42, 42)
                .addComponent(AttButton)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArchDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchDevActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EditDev().setVisible(true);
            }
        });
    }//GEN-LAST:event_ArchDevActionPerformed

    private void PovButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PovButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PoverkaPov().setVisible(true);
            }
        });
    }//GEN-LAST:event_PovButtonActionPerformed

    private void IzmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzmButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PoverkaIzm().setVisible(true);
            }
        });
    }//GEN-LAST:event_IzmButtonActionPerformed

    private void AttButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Attestation().setVisible(true);
            }
        });
    }//GEN-LAST:event_AttButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Arch;
    private javax.swing.JMenuItem ArchDev;
    private javax.swing.JButton AttButton;
    private javax.swing.JButton IzmButton;
    private javax.swing.JButton PovButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton repButton;
    // End of variables declaration//GEN-END:variables

}
